"""migrate

Revision ID: 001996bd12ff
Revises: 
Create Date: 2020-06-12 16:03:31.705427

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '001996bd12ff'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tweets',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tweet', sa.String(length=280), nullable=False),
    sa.Column('url', sa.String(length=200), nullable=False),
    sa.Column('result', sa.String(length=4), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tweets_url'), 'tweets', ['url'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tweets_url'), table_name='tweets')
    op.drop_table('tweets')
    # ### end Alembic commands ###
